Repository easybuilders/easybuild, pull requests merged in 2018-04, with the labels that each got.

#422 fix documented order of type/value in checksum tuple
  docs/Writing_easyconfig_files.rst
Labels: bug fix

#420 add documentation for new --fetch option
  docs/Partial_installations.rst
Labels: enhancement

#423 clarify that RPATH support is now stable
  docs/Experimental_features.rst
  docs/RPATH-support.rst
Labels: bug fix

#414 add documentation on support for generation (Singularity) container recipes & images
  docs/Configuration.rst
  docs/Containers.rst
  docs/Experimental_features.rst
  docs/index.rst
Labels: enhancement

#424 add documentation on --container-tmpdir
  docs/Changelog.rst
  docs/Containers.rst
  docs/conf.py
Labels: enhancement

#427 update release notes for EasyBuild v3.6.0
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#428 release EasyBuild v3.6.0
  setup.py
Labels: update
