Repository easybuilders/easybuild, pull requests merged in 2018-11, with the labels that each got.

#466 document deprecation of 'skip_symlinks' in adjust_permissions + custom PythonPackage easyconfig paramters
  docs/Deprecated-functionality.rst
Labels: update

#467 update --job documentation to also cover support for Slurm job backend
  docs/Changelog.rst
  docs/Deprecated-functionality.rst
  docs/Submitting_jobs.rst
  docs/conf.py
Labels: update

#468 add documentation on deprecated easyconfigs/toolchains
  docs/Changelog.rst
  docs/Deprecated-easyconfigs.rst
  docs/conf.py
  docs/index.rst
Labels: enhancement

#469 Update Configuration.rst
  docs/Configuration.rst
Labels: bug fix

#470 document support for filtering dependencies by version
  docs/Manipulating_dependencies.rst
Labels: enhancement
