Repository easybuilders/easybuild, pull requests merged in 2018-05, with the labels that each got.

#431 update list of maintainers to reflect that they now all have admin access to all EasyBuild repositories
  docs/Maintainers.rst
Labels: update

#433 Update Maintainers.rst
  docs/Maintainers.rst
Labels: bug fix

#432 remark that git-working-dirs-path option can be set in the config file
  docs/Integration_with_GitHub.rst
Labels: enhancement

#434 add Åke as EasyBuild maintainer
  docs/Maintainers.rst
Labels: enhancement, update

#436 add Bart as EasyBuild maintainer
  docs/Maintainers.rst
Labels: update

#437 auto-update documentation for EasyBuild v3.6.1
  docs/api/easybuild.toolchains.fosscuda.rst
  docs/api/easybuild.toolchains.rst
  docs/scripts/update-all-docs.sh
  docs/version-specific/Supported_software.rst
  docs/version-specific/config_file_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
Labels: update

#440 release EasyBuild v3.6.1
  docs/Maintainers.rst
  docs/Release_notes.rst
  docs/api/easybuild.toolchains.fosscuda.rst
  docs/api/easybuild.toolchains.rst
  docs/scripts/update-all-docs.sh
  docs/version-specific/Supported_software.rst
  docs/version-specific/config_file_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
  setup.py
Labels: update
