Repository easybuilders/easybuild, pull requests merged in 2019-11, with the labels that each got.

#557 also mention EnvironmentModules as possible configuration value for ---modules-tool
  docs/Configuration.rst
  docs/Installation.rst
Labels: bug fix, documentation

#558 add subsection on use of wildcards in --external-modules-metadata
  docs/Using_external_modules.rst
Labels: documentation

#559 doc updates for EasyBuild v4.1.0
  docs/Backup_modules.rst
  docs/Deprecated-functionality.rst
  docs/conf.py
Labels: update

#561 Add example pip commands for GitHub integration
  docs/Integration_with_GitHub.rst
Labels: documentation
