Repository easybuilders/easybuild, pull requests merged in 2019-12, with the labels that each got.

#572 auto-update docs for EasyBuild v4.1.0 release
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
Labels: update

#570 update release notes for EasyBuild v4.1.0
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#574 release EasyBuild v4.1.0
  docs/Backup_modules.rst
  docs/Changelog.rst
  docs/Deprecated-functionality.rst
  docs/Integration_with_GitHub.rst
  docs/Release_notes.rst
  docs/Using_external_modules.rst
  docs/conf.py
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  setup.py
Labels: update

#575 sync develop with master
  docs/Installation.rst
  docs/Release_notes.rst
  setup.py
Labels: update

#567 Travis CI: Add Python 3.8 to the testing
  .travis.yml
Labels: enhancement

#582 import simple_option from easybuild.base instead of vsc.utils
  docs/scripts/gen_api_docs.py
  docs/scripts/gen_easyblocks_docs.py
Labels: bug fix

#581 Travis CI: Test for Python syntax errors and undefined names
  .travis.yml
Labels: enhancement
