Repository easybuilders/easybuild, pull requests merged in 2019-01, with the labels that each got.

#478 + --check-style mention
  docs/Code_style.rst
Labels: enhancement

#479 add definitions of 2019a common toolchains
  docs/Changelog.rst
  docs/Common-toolchains.rst
  docs/conf.py
Labels: documentation

#480 update release notes for EasyBuild v3.8.1 & bump version
  docs/Release_notes.rst
  setup.py
Labels: update

#482 auto-update docs for EasyBuild v3.8.1
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
Labels: documentation, update
