Repository easybuilders/easybuild, pull requests merged in 2019-05, with the labels that each got.

#507 fix 'Python 2.x' classifiers + add a few more
  setup.py
Labels: bug fix, enhancement

#506 setup.py: Update the PyPI trove classifiers
  setup.py
Labels: bug fix, update

#509 auto-update version-specific documentation for EasyBuild v3.9.1
  .travis.yml
  docs/Containers.rst
  docs/Implementing-easyblocks.rst
  docs/Installation_Alternative.rst
  docs/Release_notes.rst
  docs/scripts/update-all-docs.sh
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
Labels: documentation

#508 document support for 'eb --missing-modules'
  docs/Using_the_EasyBuild_command_line.rst
Labels: documentation

#510 update release notes for EasyBuild v3.9.1
  .travis.yml
  docs/Changelog.rst
  docs/Maintainers.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#511 release EasyBuild v3.9.1
  .travis.yml
  docs/Changelog.rst
  docs/Containers.rst
  docs/Implementing-easyblocks.rst
  docs/Installation_Alternative.rst
  docs/Maintainers.rst
  docs/Release_notes.rst
  docs/Using_the_EasyBuild_command_line.rst
  docs/conf.py
  docs/scripts/update-all-docs.sh
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  setup.py
Labels: update

#512 update docs on container integration for upcoming EasyBuild v3.8.2
  docs/Containers.rst
Labels: update

#513 update docs on container integration w.r.t. enhanced --containers-base-config
  docs/Containers.rst
Labels: documentation, update
