Repository easybuilders/easybuild, pull requests merged in 2020-10, with the labels that each got.

#652 Fix broken create index command
  docs/Easyconfigs_index.rst
Labels: bug fix, documentation

#653 auto-update docs for EasyBuild v4.3.1
  docs/version-specific/Supported_software.rst
  docs/version-specific/config_file_constants.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
Labels: documentation, update

#654 update release notes for EasyBuild v4.3.1
  docs/Release_notes.rst
Labels: update

#655 release EasyBuild v4.3.1
  docs/Easyconfigs_index.rst
  docs/version-specific/Supported_software.rst
  docs/version-specific/config_file_constants.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
  setup.py
Labels: update

#656 publish release notes for EasyBuild v4.3.1
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: documentation, update
