Repository easybuilders/easybuild, pull requests merged in 2020-05, with the labels that each got.

#620 add readthedocs configuration file
  .readthedocs.yml
Labels: bug fix, documentation

#612 add script to create source tarballs for EasyBuild releases
  .github/workflows/doc_build.yml
  .github/workflows/scripts.yml
  scripts/create_source_tarball.sh
Labels: enhancement

#623 update list of known toolchains
  docs/eb_list_toolchains.rst
  docs/scripts/update-all-docs.sh
  docs/version-specific/eb_list_toolchains.txt
  docs/version-specific/toolchains.rst
Labels: documentation, update

#627 auto-update docs for EasyBuild v4.2.1
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
Labels: update

#626 update release notes for EasyBuild v4.2.1
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: documentation, update

#628 release EasyBuild v4.2.1
  .github/workflows/doc_build.yml
  .github/workflows/scripts.yml
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
  docs/eb_list_toolchains.rst
  docs/scripts/update-all-docs.sh
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/eb_list_toolchains.txt
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchains.rst
  scripts/create_source_tarball.sh
  setup.py
Labels: update

#629 add definitions for foss/2020a + intel/2020a common toolchains to docs
  docs/Common-toolchains.rst
Labels: documentation, update
