Repository easybuilders/easybuild, pull requests merged in 2020-02, with the labels that each got.

#590 add Lars as EasyBuild maintainer
  docs/Maintainers.rst
Labels: documentation

#593 add Alex as EasyBuild maintainer
  docs/Maintainers.rst
Labels: documentation

#594 add Caspar as EasyBuild maintainer
  docs/Maintainers.rst
Labels: documentation

#595 add Miguel as release manager
  docs/Maintainers.rst
Labels: documentation

#597 Add GitHub Action tests
  .github/workflows/check_with_codespell.sh
  .github/workflows/doc_build.yml
Labels: enhancement

#600 add references to more information w.r.t. toolchains + move up link to common toolchains page on landing page
  docs/Common-toolchains.rst
  docs/Concepts_and_Terminology.rst
  docs/index.rst
Labels: documentation

#602 fix marker for indicating what is installed in the output of -D
  docs/Using_the_EasyBuild_command_line.rst
Labels: bug fix, documentation

#604 Updating WRF examples with output from EB 4.1.1 and foss/2018b
  docs/Typical_workflow_example_with_WRF.rst
Labels: documentation, update
