Repository easybuilders/easybuild, pull requests merged in 2020-12, with the labels that each got.

#662 add definition for 2020b common toolchains
  docs/Common-toolchains.rst
Labels: documentation

#663 auto-update docs for EasyBuild v4.3.2
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
Labels: documentation, update

#665 release EasyBuild v4.3.2
  docs/Changelog.rst
  docs/Common-toolchains.rst
  docs/Contributing.rst
  docs/Easystack-files.rst
  docs/Experimental_features.rst
  docs/Release_notes.rst
  docs/conf.py
  docs/index.rst
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
  setup.py
Labels: update
