Repository easybuilders/easybuild, pull requests merged in 2020-04, with the labels that each got.

#606 clarify usage of git_config
  docs/Writing_easyconfig_files.rst
Labels: documentation

#607 add documentation for --include-easyblocks-from-pr
  docs/Including_additional_Python_modules.rst
  docs/Integration_with_GitHub.rst
Labels: documentation

#610 add documentation for EasyBuild installation locks
  docs/Locks.rst
  docs/index.rst
Labels: documentation

#611 add doc page on easyconfigs index
  docs/Easyconfigs_index.rst
  docs/index.rst
Labels: documentation

#613 auto-update documentation for EasyBuild v4.2.0
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
Labels: documentation, update

#614 update release notes for EasyBuild v4.2.0
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#615 release EasyBuild v4.2.0
  docs/Changelog.rst
  docs/Easyconfigs_index.rst
  docs/Including_additional_Python_modules.rst
  docs/Integration_with_GitHub.rst
  docs/Locks.rst
  docs/Release_notes.rst
  docs/Writing_easyconfig_files.rst
  docs/conf.py
  docs/index.rst
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  setup.py
Labels: update

#616 document of use 'keep_git_dir' in 'git_config' spec for sources
  docs/Writing_easyconfig_files.rst
Labels: documentation, update
