Repository easybuilders/easybuild, pull requests merged in 2021-06, with the labels that each got.

#705 update overview of common toolchains for foss/2021a + intel/2021a
  docs/Common-toolchains.rst
Labels: documentation, update

#703 auto-update docs for EasyBuild v4.4.0
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
Labels: update

#707 update release notes and changelog for EasyBuild v4.4.0 + bump version to 4.4.0
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: documentation, update

#708 release EasyBuild v4.4.0
  .travis.yml
  docs/Changelog.rst
  docs/Common-toolchains.rst
  docs/Deprecated-functionality.rst
  docs/Installation.rst
  docs/Packaging_support.rst
  docs/Python-2-3-compatibility.rst
  docs/Release_notes.rst
  docs/Removed-functionality.rst
  docs/conf.py
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
  setup.py
Labels: update

#709 fix status badge in README: use GitHub Actions workflow rather than Travis CI
  README.rst
Labels: bug fix

#711 add @SebastianAchilles as EasyBuild maintainer
  docs/Maintainers.rst
Labels: documentation

#712 add @bedroge as EasyBuild maintainer
  docs/Maintainers.rst
Labels: documentation

#714 Add documentation and example for write-module-hook
  docs/Deprecated-functionality.rst
  docs/Hooks.rst
Labels: documentation, enhancement

#715 correct statement on return value of module write hook
  docs/Hooks.rst
Labels: bug fix, documentation

#716 clarify return value of module write hook
  docs/Hooks.rst
Labels: bug fix

#700 Fix doku about Github tokens
  docs/Integration_with_GitHub.rst
Labels: bug fix, documentation

#718 revamp EasyBuild installation docs: recommend pip or (manual) 3-stage bootstrap with pip + EasyBuild
  docs/Installation.rst
Labels: documentation, update

#719 Link to pip instead of bootstrap for installation on EasyBuild website
  index.html
Labels: bug fix, documentation

#720 correct the a tag closure
  index.html
Labels: bug fix
