Repository easybuilders/easybuild, pull requests merged in 2021-04, with the labels that each got.

#686 auto-update documentation for EasyBuild v4.3.4
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
Labels: documentation, update

#687 update release notes and changelog for EasyBuild v4.3.4 + bump version to 4.3.4
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#689 release EasyBuild v4.3.4
  docs/Integration_with_GitHub.rst
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
  setup.py
Labels: update

#690 add EasyBuild v4.3.4 release notes
  .github/workflows/doc_build.yml
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: documentation, update

#691 make sure that release notes are in place for current EasyBuild version
  .github/workflows/doc_build.yml
Labels: documentation, enhancement

#692 update setup.py to indicate compatibility with Python 3.8 and 3.9
  setup.py
Labels: update

#693 Change unified diff command
  docs/Writing_easyconfig_files.rst
Labels: enhancement
