Repository easybuilders/easybuild, pull requests merged in 2021-02, with the labels that each got.

#673 Prevent wrong dash appearing in doc
  docs/Installation.rst
  docs/Integration_with_GitHub.rst
  docs/Using_the_EasyBuild_command_line.rst
Labels: bug fix

#674 Adding conditional symlinking of lua posix lib in GH workflow script
  .github/workflows/scripts.yml
Labels: bug fix

#675 auto-update docs for EasyBuild v4.3.3
  docs/api/framework.easyblock.rst
  docs/api/framework.easyconfig.constants.rst
  docs/api/framework.easyconfig.default.rst
  docs/api/framework.easyconfig.easyconfig.rst
  docs/api/framework.easyconfig.format.convert.rst
  docs/api/framework.easyconfig.format.format.rst
  docs/api/framework.easyconfig.format.one.rst
  docs/api/framework.easyconfig.format.pyheaderconfigobj.rst
  docs/api/framework.easyconfig.format.rst
  docs/api/framework.easyconfig.format.two.rst
  docs/api/framework.easyconfig.format.version.rst
  docs/api/framework.easyconfig.format.yeb.rst
  docs/api/framework.easyconfig.licenses.rst
  docs/api/framework.easyconfig.parser.rst
  docs/api/framework.easyconfig.rst
  docs/api/framework.easyconfig.style.rst
  docs/api/framework.easyconfig.templates.rst
  docs/api/framework.easyconfig.tools.rst
  docs/api/framework.easyconfig.tweak.rst
  docs/api/framework.easyconfig.types.rst
  docs/api/framework.easystack.rst
  docs/api/framework.extension.rst
  docs/api/framework.extensioneasyblock.rst
  docs/api/framework.rst
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
Labels: documentation, update

#677 use 'main' rather than 'master' branch in test suite configuration
  .github/workflows/scripts.yml
  docs/Archived-easyconfigs.rst
  docs/Contributing.rst
  docs/Implementing-easyblocks.rst
  docs/Installation.rst
  docs/Installation_Alternative.rst
  docs/Unit-tests.rst
  docs/Useful-scripts.rst
  docs/Using_external_modules.rst
  docs/Writing_easyconfig_files.rst
  scripts/create_source_tarball.sh
Labels: change

#678 release EasyBuild v4.3.3
  .github/workflows/check_with_codespell.sh
  .github/workflows/scripts.yml
  README.rst
  docs/Archived-easyconfigs.rst
  docs/Changelog.rst
  docs/Contributing.rst
  docs/Implementing-easyblocks.rst
  docs/Installation.rst
  docs/Installation_Alternative.rst
  docs/Release_notes.rst
  docs/Unit-tests.rst
  docs/Useful-scripts.rst
  docs/Using_external_modules.rst
  docs/Writing_easyconfig_files.rst
  docs/api/framework.easyblock.rst
  docs/api/framework.easyconfig.constants.rst
  docs/api/framework.easyconfig.default.rst
  docs/api/framework.easyconfig.easyconfig.rst
  docs/api/framework.easyconfig.format.convert.rst
  docs/api/framework.easyconfig.format.format.rst
  docs/api/framework.easyconfig.format.one.rst
  docs/api/framework.easyconfig.format.pyheaderconfigobj.rst
  docs/api/framework.easyconfig.format.rst
  docs/api/framework.easyconfig.format.two.rst
  docs/api/framework.easyconfig.format.version.rst
  docs/api/framework.easyconfig.format.yeb.rst
  docs/api/framework.easyconfig.licenses.rst
  docs/api/framework.easyconfig.parser.rst
  docs/api/framework.easyconfig.rst
  docs/api/framework.easyconfig.style.rst
  docs/api/framework.easyconfig.templates.rst
  docs/api/framework.easyconfig.tools.rst
  docs/api/framework.easyconfig.tweak.rst
  docs/api/framework.easyconfig.types.rst
  docs/api/framework.easystack.rst
  docs/api/framework.extension.rst
  docs/api/framework.extensioneasyblock.rst
  docs/api/framework.rst
  docs/conf.py
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
  scripts/create_source_tarball.sh
  setup.py
Labels: update
