Repository easybuilders/easybuild, pull requests merged in 2021-07, with the labels that each got.

#724 auto-update documentation for EasyBuild v4.4.1
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
Labels: documentation, update

#725 update release notes and changelog for EasyBuild v4.4.1 + bump version to 4.4.1
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: documentation, update

#726 release Easybuild v4.4.1
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
  setup.py
Labels: update

#728 remove Python 2.6 from list of supported Python versions in setup.py
  setup.py
Labels: bug fix
