Repository easybuilders/easybuild, pull requests merged in 2022-10, with the labels that each got.

#827 update documentation to use `SYSTEM` template constant for system-toolchain dependencies
  docs/Wrapping_dependencies.rst
  docs/Writing_easyconfig_files.rst
Labels: update, documentation

#830 update release notes and changelog for EasyBuild v4.6.2 + bump version to 4.6.2
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#831 release EasyBuild v4.6.2
  docs/Changelog.rst
  docs/Common-toolchains.rst
  docs/Release_notes.rst
  docs/Wrapping_dependencies.rst
  docs/Writing_easyconfig_files.rst
  docs/conf.py
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  setup.py
Labels: update

#834 sync auto-update of docs for EasyBuild v4.6.2 to main branch
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
Labels: bug fix, documentation
