Repository easybuilders/easybuild, pull requests merged in 2022-09, with the labels that each got.

#816 add Sebastian as release manager
  docs/Implementing-easyblocks.rst
  docs/Maintainers.rst
  docs/Release_notes.rst
Labels: documentation

#819 auto-update docs for EasyBuild v4.6.1
  docs/Common-toolchains.rst
  docs/version-specific/Supported_software.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
Labels: update, documentation

#820 update release notes and changelog for EasyBuild v4.6.1 + bump version to 4.6.1
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#821 release EasyBuild v4.6.1
  docs/Changelog.rst
  docs/Implementing-easyblocks.rst
  docs/Maintainers.rst
  docs/Release_notes.rst
  docs/conf.py
  setup.py
Labels: update
