Repository easybuilders/easybuild, pull requests merged in 2022-01, with the labels that each got.

#773 Update Alan's email address (again)
  docs/Maintainers.rst
Labels: bug fix, documentation

#775 auto-update docs for EasyBuild v4.5.2
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/generic_easyblocks.rst
Labels: update, documentation

#776 update release notes and changelog for EasyBuild v4.5.2 + bump version to 4.5.2
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update, documentation

#777 release EasyBuild v4.5.2
  docs/Changelog.rst
  docs/Experimental_features.rst
  docs/Release_notes.rst
  docs/conf.py
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/generic_easyblocks.rst
  setup.py
Labels: update
