Repository easybuilders/easybuild, pull requests merged in 2022-02, with the labels that each got.

#779 add Jasper Grimm as EasyBuild maintainer
  docs/Maintainers.rst
Labels: update, documentation

#778 specify easybuild.io as EasyBuild homepage in setup.py + docs landing page
  docs/index.rst
  setup.py
Labels: bug fix, documentation

#782 fix typo in 'Consistency' in section title
  docs/Configuration.rst
  setup.py
Labels: bug fix, documentation

#783 auto-update docs for EasyBuild v4.5.3
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
Labels: update, documentation

#781 Add Docker command examples
  docs/Containers.rst
Labels: update, documentation

#784 indicate compatibility with Python 3.10 in setup.py
  setup.py
Labels: update

#785 update release notes and changelog for EasyBuild v4.5.3 + bump version to 4.5.3
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#786 release EasyBuild v4.5.3
  docs/Changelog.rst
  docs/Configuration.rst
  docs/Installing-Lmod-without-root-permissions.rst
  docs/Release_notes.rst
  docs/Writing_easyconfig_files.rst
  docs/conf.py
  docs/index.rst
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  setup.py
Labels: update
