Repository easybuilders/easybuild, pull requests merged in 2022-11, with the labels that each got.

#839 add EasyBuild logos, old and new
  .github/workflows/check_with_codespell.sh
  logo/old_logo_2012-2022/easybuild_logo.pdf
  logo/old_logo_2012-2022/easybuild_logo.png
  logo/old_logo_2012-2022/easybuild_logo_alpha.png
  logo/old_logo_2012-2022/easybuild_logo_blocks.png
  logo/old_logo_2012-2022/easybuild_logo_white.png
  logo/old_logo_2012-2022/easybuild_tech_talks.png
  logo/pdf/easybuild_logo_2022_horizontal_dark_bg.pdf
  logo/pdf/easybuild_logo_2022_horizontal_light_bg.pdf
  logo/pdf/easybuild_logo_2022_horizontal_no_slogal_dark_bg.pdf
  logo/pdf/easybuild_logo_2022_horizontal_no_slogal_light_bg.pdf
  logo/pdf/easybuild_logo_2022_vertical_dark_bg.pdf
  logo/pdf/easybuild_logo_2022_vertical_light_bg.pdf
  logo/pdf/easybuild_logo_2022_vertical_no_slogal_dark_bg.pdf
  logo/pdf/easybuild_logo_2022_vertical_no_slogal_light_bg.pdf
  logo/png/easybuild_logo_2022_horizontal_dark_bg.png
  logo/png/easybuild_logo_2022_horizontal_dark_bg_transparent.png
  logo/png/easybuild_logo_2022_horizontal_light_bg.png
  logo/png/easybuild_logo_2022_horizontal_light_bg_transparent.png
  logo/png/easybuild_logo_2022_horizontal_no_slogan_dark_bg.png
  logo/png/easybuild_logo_2022_horizontal_no_slogan_dark_bg_transparent.png
  logo/png/easybuild_logo_2022_horizontal_no_slogan_light_bg.png
  logo/png/easybuild_logo_2022_horizontal_no_slogan_light_bg_transparent.png
  logo/png/easybuild_logo_2022_vertical_dark_bg.png
  logo/png/easybuild_logo_2022_vertical_dark_bg_transparent.png
  logo/png/easybuild_logo_2022_vertical_light_bg.png
  logo/png/easybuild_logo_2022_vertical_light_bg_transparent.png
  logo/png/easybuild_logo_2022_vertical_no_slogan_dark_bg.png
  logo/png/easybuild_logo_2022_vertical_no_slogan_dark_bg_transparent.png
  logo/png/easybuild_logo_2022_vertical_no_slogan_light_bg.png
  logo/png/easybuild_logo_2022_vertical_no_slogan_light_bg_transparent.png
Labels: update, documentation

#840 use new EasyBuild logo in README
  README.rst
Labels: update, documentation

#841 use new EasyBuild logo in documentation
  docs/easybuild_logo_alpha.png
Labels: update, documentation

#832 Updated easystack documentation
  docs/Easystack-files.rst
Labels: documentation

#843 Cancel GithubAction runs for outdated commits
  .github/workflows/doc_build.yml
  .github/workflows/linting.yml
  .github/workflows/scripts.yml
Labels: enhancement
