Repository easybuilders/easybuild, pull requests merged in 2022-03, with the labels that each got.

#789 document 'clone_into' field in git_config that can be used in 'sources' easyconfig parameter
  docs/Writing_easyconfig_files.rst
Labels: documentation

#791 auto-update docs for EasyBuild v4.5.4
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
Labels: update, documentation

#792 update release notes and changelog for EasyBuild v4.5.4 + bump version to 4.5.4
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#793 release EasyBuild v4.5.4
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/Writing_easyconfig_files.rst
  docs/conf.py
  docs/version-specific/Supported_software.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
  setup.py
Labels: update
