Repository easybuilders/easybuild, pull requests merged in 2023-01, with the labels that each got.

#845 update overview of common toolchains with foss/2022b and intel/2022b
  docs/Common-toolchains.rst
Labels: update, documentation

#846 auto-update docs for EasyBuild v4.7.0
  docs/version-specific/Supported_software.rst
  docs/version-specific/config_file_constants.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_license_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
Labels: update, documentation

#847 update release notes and changelog for EasyBuild v4.7.0 + bump version to 4.7.0
  docs/Changelog.rst
  docs/Release_notes.rst
  docs/conf.py
Labels: update

#848 release EasyBuild v4.7.0
  .github/workflows/doc_build.yml
  .github/workflows/linting.yml
  .github/workflows/scripts.yml
  docs/Changelog.rst
  docs/Common-toolchains.rst
  docs/Easystack-files.rst
  docs/Release_notes.rst
  docs/conf.py
  docs/version-specific/Supported_software.rst
  docs/version-specific/config_file_constants.rst
  docs/version-specific/easyblocks.rst
  docs/version-specific/easyconfig_constants.rst
  docs/version-specific/easyconfig_license_constants.rst
  docs/version-specific/easyconfig_parameters.rst
  docs/version-specific/easyconfig_templates.rst
  docs/version-specific/generic_easyblocks.rst
  docs/version-specific/help.rst
  docs/version-specific/toolchain_opts.rst
  docs/version-specific/toolchains.rst
  setup.py
Labels: update

#849 update version to 4.7.0 in setup.py
  setup.py
Labels: update

#854 correct date in changelog entry for EB 4.7.0
  docs/Changelog.rst
Labels: bug fix, documentation

#855 Fix indentation in Easystack examples
  docs/Easystack-files.rst
Labels: bug fix, documentation

#856 fix website/docs links in README + don't mention IRC anymore
  README.rst
Labels: bug fix, documentation
